# ================= MAIN DOMAIN HTTP =================
server {
    listen 80;
    server_name grammrlyst.in www.grammrlyst.in;

    location = / {
        return 302 /docs;
    }

    location / {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# ================= MAIN DOMAIN HTTPS =================
server {
    listen 443 ssl;
    server_name grammrlyst.in www.grammrlyst.in;

    ssl_certificate /etc/letsencrypt/live/grammrlyst.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grammrlyst.in/privkey.pem;

    location / {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# ================= PHPMYADMIN HTTP =================
server {
    listen 80;
    server_name pma.grammrlyst.in;

    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# ================= PHPMYADMIN HTTPS =================
server {
    listen 443 ssl;
    server_name pma.grammrlyst.in;

    ssl_certificate /etc/letsencrypt/live/grammrlyst.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grammrlyst.in/privkey.pem;

    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}