- name: Deploy on server
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
      set -e

      if [ ! -d '${{ secrets.SERVER_PATH }}' ]; then
        git clone https://github.com/mohit9710/grammrlyst-python ${{ secrets.SERVER_PATH }};
      fi

      cd ${{ secrets.SERVER_PATH }}

      git pull

      docker compose down --remove-orphans
      docker compose up -d --build

      docker image prune -f
    "