- name: Deploy on server
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
      if [ ! -d '${{ secrets.SERVER_PATH }}' ]; then
        git clone https://github.com/mohit9710/grammrlyst-python ${{ secrets.SERVER_PATH }};
      fi
      cd ${{ secrets.SERVER_PATH }}
      git pull
      docker-compose down
      docker-compose up -d --build
    "